import settings
from gui import colors

ALIGN_LEFT = 0
ALIGN_RIGHT = settings.SCREEN_WIDTH
ALIGN_TOP = 0
ALIGN_BOTTOM = settings.SCREEN_HEIGHT
ALIGN_CENTER = settings.SCREEN_WIDTH // 2

X_BLOCK_WIDTH = settings.SCREEN_WIDTH / 12
X_0 = 0
X_1 = X_BLOCK_WIDTH
X_2 = 2 * X_BLOCK_WIDTH
X_3 = 3 * X_BLOCK_WIDTH
X_4 = 4 * X_BLOCK_WIDTH
X_5 = 5 * X_BLOCK_WIDTH
X_6 = 6 * X_BLOCK_WIDTH
X_7 = 7 * X_BLOCK_WIDTH
X_8 = 8 * X_BLOCK_WIDTH
X_9 = 9 * X_BLOCK_WIDTH
X_10 = 10 * X_BLOCK_WIDTH
X_11 = 11 * X_BLOCK_WIDTH
X_12 = 12 * X_BLOCK_WIDTH

Y_BLOCK_WIDTH = settings.SCREEN_HEIGHT / 12
Y_0 = 0
Y_1 = Y_BLOCK_WIDTH
Y_2 = 2 * Y_BLOCK_WIDTH
Y_3 = 3 * Y_BLOCK_WIDTH
Y_4 = 4 * Y_BLOCK_WIDTH
Y_5 = 5 * Y_BLOCK_WIDTH
Y_6 = 6 * Y_BLOCK_WIDTH
Y_7 = 7 * Y_BLOCK_WIDTH
Y_8 = 8 * Y_BLOCK_WIDTH
Y_9 = 9 * Y_BLOCK_WIDTH
Y_10 = 10 * Y_BLOCK_WIDTH
Y_11 = 11 * Y_BLOCK_WIDTH
Y_12 = 12 * Y_BLOCK_WIDTH

MARGIN_TOP = 10
MARGIN_BOTTOM = 10
MARGIN_LEFT = 10
MARGIN_RIGHT = 10

WINDOW_WIDTH_XS = X_BLOCK_WIDTH
WINDOW_WIDTH_SM = 2 * X_BLOCK_WIDTH
WINDOW_WIDTH_MD = 4 * X_BLOCK_WIDTH
WINDOW_WIDTH_LG = 8 * X_BLOCK_WIDTH
WINDOW_WIDTH_XL = 10 * X_BLOCK_WIDTH

WINDOW_HEIGHT_XS = Y_BLOCK_WIDTH
WINDOW_HEIGHT_SM = 2 * Y_BLOCK_WIDTH
WINDOW_HEIGHT_MD = 4 * Y_BLOCK_WIDTH
WINDOW_HEIGHT_LG = 8 * Y_BLOCK_WIDTH
WINDOW_HEIGHT_XL = 12 * Y_BLOCK_WIDTH

WINDOW_BACKGROUND_COLOR = (100, 80, 100)
WINDOW_BORDER_COLOR = colors.BLACK
TEXT_COLOR = colors.WHITE
TEXT_COLOR_DISABLED = colors.GREY
