import settings

ALIGN_LEFT = 0
ALIGN_RIGHT = settings.SCREEN_WIDTH
ALIGN_TOP = 0
ALIGN_BOTTOM = settings.SCREEN_HEIGHT
ALIGN_CENTER = settings.SCREEN_WIDTH // 2

MARGIN_TOP = 100


WINDOW_BACKGROUND_COLOR = (100, 80, 100)
WINDOW_BORDER_COLOR = (0, 0, 0)
TEXT_COLOR = (255, 255, 255)
